### ISSUE TITLE
Add i18n to go-humanize

### ISSUE THREAD

**Issue by jfbus** [dustin/go-humanize#12]
Here is a proposal to support i18n :
- Add new types

```
type BaseHumanizer {}
type EnglishHumanizer {
    BaseHumanizer
}
var Default EnglishHumanizer
var English EnglishHumanizer
```
- Move all funcs to StandardHumanizer or EnglishHumanizer

```
func (h *BaseHumanizer) Ftoa(num float64) string {
    [...]
}
func Ftoa(num float64) string {
    return Default.Ftoa(num)
}

func (h *EnglishHumanizer) Ordinal(x int) string {
    [...]
}

func Ordinal(x int) string {
    return DefaultHumanizer.Ordinal(x)
}
```
- Add the definition for french :

```
type FrenchHumanizer {
    BaseHumanizer
}
var French FrenchHumanizer

func (h *FrenchHumanizer) Ordinal(x int) string {
    [...]
}
```

Usage :

```
fmt.Println(humanizer.Ordinal(1)) => "1st"
fmt.Println(humanizer.Default.Ordinal(1)) => "1st"
fmt.Println(humanizer.English.Ordinal(1)) => "1st"
fmt.Println(humanizer.French.Ordinal(1)) => "1er"
```

**Comment by shurcooL** [comment]
@dustin, is i18n in scope for this project or out of scope?

**Comment by jfbus** [comment]
If necessary, I can update my PR.

**Comment by shurcooL** [comment]
Personally, I don't think we should add i18n here. The amount of volume and work to create and maintain it would be huge, and overshadow the size of this entire library as it is now. It's relatively small and focused because it's English-only.

I think that if someone wanted an i18n-capable version of this, it would be best done as a new separate package (and go-humanize README can link to it). When a feature request is more than 100% of scope of existing project, it doesn't feel right to just add it in.

So, I would advise against doing this. If it's not going to be actively developed and maintained, a half-baked partial i18n support is only going to complicate the library, and not provide enough value to people who actually want to make use of it. It's better to stay small and focused and high quality.

Of course, it's up to @dustin, but I'm judging by lack of response and progress on this issue/PR after 3 years that it's not going to be a good fit.

What do you think about making adding it to your own version of a similar library @jfbus? That way, you can also change the APIs to be a better fit, if neccessary.

**Comment by dustin** [comment]
I agree.  Every time I've thought about how to do this, it's been essentially what you described -- write a new library.  There's so much involved in dealing with all the different locale-specific ways to represent the data.  There are a few high level formatters that can be rearranged in specific applications, but I haven't been able to figure out how to fit in localized variations (and I'm not even that familiar with most of them, just enough to make it seem really complex).

**Comment by jfbus** [comment]
OK. I'll try to work on an i18n compatible lib.

**Comment by PabloCastellano** [comment]
Is there any similar lib with i18n support nowadays?
