### ISSUE TITLE
Space between numerical value and unit symbol for SI output

### ISSUE THREAD

**Issue by spellgen** [dustin/go-humanize#21]
Very nice collection here. Just a niggle - SI convention calls for a space between the number and the unit: 1 m, 10 kg, 123 mS ... etc

http://physics.nist.gov/Pubs/SP811/sec07.html

**Comment by kyle-f** [comment]
Seconded-- should be the same for bytes.

**Comment by shurcooL** [comment]
I think I'm in favor.

**Comment by dustin** [comment]
It'd be fairly hard to make this configurable.  I suppose it's the right thing to do, but it will take up seemingly unnecessary space in areas I use it where space is scarce and seemingly will just reduce clarity by taking logically grouped units and separating them into multiple parts.

e.g., instead of

    1MB 1KB 1MB 1MB 1KB 1GB 1MB

I'd have

    1 MB 1 KB 1 MB 1 MB 1 KB 1 GB 1 MB

**Comment by kyle-f** [comment]
dustin, it only reduces clarity when you have it ambiguously spaced like in your example. These are the SI conventions. Right now I'm using regex to put the space in there!

**Comment by shurcooL** [comment]
:+1:
