### ISSUE TITLE
Allow user to define custom time format

### ISSUE THREAD

**Issue by hurf** [dustin/go-humanize#25]
I'm using go-humanize to format time. But it seems output like '12 seconds ago' is too long for me. So I'm thinking if we can allow users to customize their own output format?

**Comment by shurcooL** [comment]
How would you specify it?

Unless you have a good proposal to do this, it seems like it's be shorter to simply implement what you want yourself. As an example, I wanted something like `humanize.Time` except to have it always say "less than a minute ago" for time spans of less than a minute. I just [wrote it](https://github.com/shurcooL/gtdo/commit/c38f6214e40dbbfbc6ed65a9beb01a040ec59298), the func was 4 lines of code.

**Comment by shurcooL** [comment]
Also, have you seen [`humanize.RelTime`](https://godoc.org/github.com/dustin/go-humanize#RelTime)? It lets you specify custom labels for times that earlier and later.

**Comment by hurf** [comment]
@shurcooL - Thanks! Accutally I want something like '12s ago' or '21 days'(I don't want to use `week`) . I've wrote the code and will submit a PR for it.

**Comment by tj** [comment]
I'd like this as well, seems to be a common mistake that libs like this append "ago".

**Comment by shurcooL** [comment]
`humanize.Duration(n)` sounds reasonable to me at a surface glance. But please run that proposal by @dustin. It's really hard to control feature-creep in the API of this library. We still haven't even merged #26 after all this time.

**Comment by tj** [comment]
Hmm actually on second thought I do think it would be nice, I just got bit by it adding the opinionated "now" for tiny deltas

**Comment by dustin** [comment]
I'll send up a PR in a few minutes.

**Comment by dustin** [comment]
Sorry, took me a bit more than a couple of minutes to get off the bus, but I think this may do what you want.

In particular:

1. Arbitrary ranges.
2. Nanosecond precision.

The first one was I think what was being asked for in particular.

The second is required because the way it was implemented rounded everything to seconds.  The general vision of `RelTime` was to show time for humans on a page where things are meant to be presented in human scales.  `time.Duration.String()` seems well suited for the rest of these cases, but there are plenty of reasons to allow people to specify their own arbitrary boundaries.

**Comment by tj** [comment]
Understandable. I was thinking it could be something like:

```go
func Time(t time.Time) string {
	if t.Before(time.Now()) {
		return Duration(time.Now().Sub(t)) + " ago"
	} else {
		return Duration(t.Sub(time.Now())) + " from now"
	}
}
```

Then if you have a different domain like mine where you'd just like to say "Resolved in X minutes" or similar it's no problem, no `strings.Trim()` required with `RelTime`.

**Comment by tj** [comment]
I guess for my case rounding up or down entire hours etc is not precise enough anyway haha, but hey 😄
