### ISSUE TITLE
Represent sizes as int64 instead of uint64

### ISSUE THREAD

**Issue by ammario** [dustin/go-humanize#67]
I think this package should accept and return sizes typed `int64` instead of `uint64`.

The standard library uses int64 to represent sizes, so I do a lot of casting when using this package.

Thanks.

**Comment by dustin** [comment]
I understand the inconvenience, but that's a fairly large backwards incompatible change.  Conceptually, the number of bytes in something is non-negative, so unsigned made sense at the time.  Having to convert from int64 or int or float64 or whatever in order to format a number is an unfortunate language constraint, but it's not a logical flaw in the concept of representing bytes as non-negative numbers.

**Comment by ammario** [comment]
The breakage would be trivial to fix, and the orthogonality with the rest of the Go ecosystem would make this API significantly better. I can carry out the change, as well, if you reconsider this.

**Comment by nhooyr** [comment]
And with Go modules it doesn't have to be backwards incompatible.

**Comment by yvele** [comment]
Can this issue be reconsidered?
